### ISSUE TITLE
Error installing Rock using the bootstrap method on a Ubuntu 18.04 Docker container

### ISSUE THREAD

**Issue by CEE20** [rock-core/buildconf#11]
Ubuntu container creation
```
docker create ubuntu:18.04
docker run -it ubuntu:18.04 /bin/bash
```

Rock Installation on Docker container ubuntu 18.04

```
mkdir rock_dev
cd rock_dev
apt-get update
apt-get install wget ruby ruby-dev
wget http://rock-robotics.org/autoproj_bootstrap
ruby autoproj_bootstrap git git@github.com:rock-core/buildconf.git
```

Results in

```
root@42e9ea888239:/rock_dev#  ruby autoproj_bootstrap git git@github.com:rock-core/buildconf.git
Detected 'gem' to be /usr/bin/gem2.5
Detected bundler at /root/.local/share/autoproj/gems/ruby/2.5.0/bin/bundle
Installing autoproj in /root/.local/share/autoproj/gems/ruby/2.5.0
[DEPRECATED] The `--path` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set --local path '/root/.local/share/autoproj/gems'`, and stop using this flag
[DEPRECATED] The `--shebang` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set --local shebang '/usr/bin/ruby2.5'`, and stop using this flag
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this
application for all non-root users on this machine.
[DEPRECATED] The --binstubs option will be removed in favor of `bundle binstubs --all`
Fetching gem metadata from https://rubygems.org/......
Resolving dependencies...
Using rake 13.0.6
Using concurrent-ruby 1.1.9
Using equatable 0.7.0
Using tty-color 0.5.2
Using bundler 2.2.29
Using necromancer 0.5.1
Using thor 1.1.0
Using tty-screen 0.8.1
Using pastel 0.7.4
Using backports 3.21.0
Using tty-cursor 0.7.1
Fetching ffi 1.15.4
Using wisper 2.0.1
Using xdg 2.2.5
Using facets 3.1.0
Using tty-spinner 0.9.3
Using utilrb 3.0.1
Using tty-reader 0.7.0
Using tty-prompt 0.21.0
Using autobuild 1.22.1
Installing ffi 1.15.4 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /root/.local/share/autoproj/gems/ruby/2.5.0/gems/ffi-1.15.4/ext/ffi_c
/usr/bin/ruby2.5 -r ./siteconf20211025-3203-1jxhkj4.rb extconf.rb
checking for ffi.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/bin/$(RUBY_BASE_NAME)2.5
        --with-ffi_c-dir
        --without-ffi_c-dir
        --with-ffi_c-include
        --without-ffi_c-include=${ffi_c-dir}/include
        --with-ffi_c-lib
        --without-ffi_c-lib=${ffi_c-dir}/lib
        --enable-system-libffi
        --disable-system-libffi
        --with-libffi-config
        --without-libffi-config
        --with-pkg-config
        --without-pkg-config
/usr/lib/ruby/2.5.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /usr/lib/ruby/2.5.0/mkmf.rb:590:in `try_cpp'
        from /usr/lib/ruby/2.5.0/mkmf.rb:1097:in `block in have_header'
        from /usr/lib/ruby/2.5.0/mkmf.rb:947:in `block in checking_for'
        from /usr/lib/ruby/2.5.0/mkmf.rb:350:in `block (2 levels) in postpone'
        from /usr/lib/ruby/2.5.0/mkmf.rb:320:in `open'
        from /usr/lib/ruby/2.5.0/mkmf.rb:350:in `block in postpone'
        from /usr/lib/ruby/2.5.0/mkmf.rb:320:in `open'
        from /usr/lib/ruby/2.5.0/mkmf.rb:346:in `postpone'
        from /usr/lib/ruby/2.5.0/mkmf.rb:946:in `checking_for'
        from /usr/lib/ruby/2.5.0/mkmf.rb:1096:in `have_header'
        from extconf.rb:10:in `system_libffi_usable?'
        from extconf.rb:42:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /root/.local/share/autoproj/gems/ruby/2.5.0/extensions/x86_64-linux/2.5.0/ffi-1.15.4/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /root/.local/share/autoproj/gems/ruby/2.5.0/gems/ffi-1.15.4 for inspection.
Results logged to /root/.local/share/autoproj/gems/ruby/2.5.0/extensions/x86_64-linux/2.5.0/ffi-1.15.4/gem_make.out

  /usr/lib/ruby/2.5.0/rubygems/ext/builder.rb:92:in `run'
  /usr/lib/ruby/2.5.0/rubygems/ext/ext_conf_builder.rb:46:in `block in build'
  /usr/lib/ruby/2.5.0/tempfile.rb:295:in `open'
  /usr/lib/ruby/2.5.0/rubygems/ext/ext_conf_builder.rb:30:in `build'
  /usr/lib/ruby/2.5.0/rubygems/ext/builder.rb:164:in `block (2 levels) in build_extension'
  /usr/lib/ruby/2.5.0/rubygems/ext/builder.rb:163:in `chdir'
  /usr/lib/ruby/2.5.0/rubygems/ext/builder.rb:163:in `block in build_extension'
  /usr/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
  /usr/lib/ruby/2.5.0/rubygems/ext/builder.rb:162:in `build_extension'
  /usr/lib/ruby/2.5.0/rubygems/ext/builder.rb:201:in `block in build_extensions'
  /usr/lib/ruby/2.5.0/rubygems/ext/builder.rb:198:in `each'
  /usr/lib/ruby/2.5.0/rubygems/ext/builder.rb:198:in `build_extensions'
  /usr/lib/ruby/2.5.0/rubygems/installer.rb:791:in `build_extensions'
/root/.local/share/autoproj/gems/ruby/2.5.0/gems/bundler-2.2.29/lib/bundler/rubygems_gem_installer.rb:66:in
`build_extensions'
  /root/.local/share/autoproj/gems/ruby/2.5.0/gems/bundler-2.2.29/lib/bundler/rubygems_gem_installer.rb:26:in `install'
  /root/.local/share/autoproj/gems/ruby/2.5.0/gems/bundler-2.2.29/lib/bundler/source/rubygems.rb:199:in `install'
  /root/.local/share/autoproj/gems/ruby/2.5.0/gems/bundler-2.2.29/lib/bundler/installer/gem_installer.rb:54:in `install'
/root/.local/share/autoproj/gems/ruby/2.5.0/gems/bundler-2.2.29/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/root/.local/share/autoproj/gems/ruby/2.5.0/gems/bundler-2.2.29/lib/bundler/installer/parallel_installer.rb:186:in
`do_install'
/root/.local/share/autoproj/gems/ruby/2.5.0/gems/bundler-2.2.29/lib/bundler/installer/parallel_installer.rb:177:in
`block in worker_pool'
  /root/.local/share/autoproj/gems/ruby/2.5.0/gems/bundler-2.2.29/lib/bundler/worker.rb:62:in `apply_func'
  /root/.local/share/autoproj/gems/ruby/2.5.0/gems/bundler-2.2.29/lib/bundler/worker.rb:57:in `block in process_queue'
  /root/.local/share/autoproj/gems/ruby/2.5.0/gems/bundler-2.2.29/lib/bundler/worker.rb:54:in `loop'
  /root/.local/share/autoproj/gems/ruby/2.5.0/gems/bundler-2.2.29/lib/bundler/worker.rb:54:in `process_queue'
/root/.local/share/autoproj/gems/ruby/2.5.0/gems/bundler-2.2.29/lib/bundler/worker.rb:91:in `block (2 levels) in
create_threads'

An error occurred while installing ffi (1.15.4), and Bundler cannot continue.

In Gemfile:
  autoproj was resolved to 2.15.0, which depends on
    rb-inotify was resolved to 0.10.1, which depends on
      ffi
FATAL: failed to install autoproj in /rock_dev/.autoproj

```

Any ideas why this is happening or how it can be solved? Am I missing some system dependencies maybe? Is there a dockerfile for this installation somewhere?

**Comment by doudou** [comment]
I've never tried to install it on a plain ubuntu docker. It seems you are missing the libffi-dev library. Try installing it before the bootstrap.

If it works, we'll add it to the bootstrap process.

**Comment by doudou** [comment]
Just had a second look at [these installation instructions](https://www.rock-robotics.org/rock-and-syskit/basics/installation.html). The `apt-get` line is `sudo apt-get install ruby ruby-dev wget build-essential`

I'm guessing that libffi-dev gets installed with build-essential

**Comment by CEE20** [comment]
Thank you @doudou, added the additional dependencies as from the second comment and it worked! Also proposed a merge request https://github.com/rock-core/rock-core.github.io/pull/25 with the updated instructions.
